version: "3"
services:
    nextjs:
        container_name: nextjs
        platform: linux/x86_64
        image: fatfriendlyseat/thefatfriendlyseat:0.9.1
        command: npm run start
        restart: unless-stopped
        volumes:
            - ./fatfriendlyseat/prisma:/usr/src/app/prisma
        env_file:
            - .env
        ports:
            - 3000:3000

    webserver:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./nginx/conf/:/etc/nginx/conf.d/:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro

    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        depends_on:
            - webserver
        

