version: "3"
services:
    nextjs:
        container_name: nextjs
        platform: linux/x86_64
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: npm run dev
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        env_file:
            - .env
        environment:
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        ports:
            - "3001:3000"
        networks:
            - web
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - nextjs
        networks:
            - web
networks:
    web:
        driver: bridge
