version: "3"
services:
    nextjs:
        container_name: nextjs
        platform: linux/x86_64
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: yarn run dev
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        env_file:
            - .env
        environment:
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        ports:
            - "3001:3000"
