version: "3"
services:
    nextjs:
        container_name: nextjs
        build:
            context: .
            dockerfile: Dockerfile
        command: yarn run start
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        env_file:
            - .env
        ports:
            - "80:3000"
