version: "3"
services:
    nextjs:
        container_name: nextjs
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        env_file:
            - .env
        ports:
            - "80:3000"
        networks:
            - web
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - nextjs
        networks:
            - web
    networks:
        web:
            driver: bridge
        

